python train.py \
        --cuda \
        --data data/ctl/ \
        --dataset ctl \
        --n_layer 6 \
        --d_model 128 \
        --n_head 8 \
        --d_head 128 \
        --d_inner 256 \
        --dropatt 0.0 \
	    --dropout 0.1 \
        --optim adam \
        --lr 2e-05 \
        --warmup_step 0 \
        --max_step 30000 \
        --tgt_len 5 \
	    --eval_tgt_len 5 \
	    --ext_len 0 \
        --scheduler cosine \
        --mem_len 0 \
	    --attn_type 2 \
        --batch_size 200 \
        --eval-interval 1000
